name: egamebook_server
description: Server which allows user to build their egamebook.
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  googleapis: any
  googleapis_auth: any
  archive: 1.0.21 # not the newest one, but newer versions have issues
  shelf: "^0.6.7"
  shelf_static: "^0.2.4"
  shelf_rest: "^0.3.4"
  uuid: "^0.5.3"
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter